### ISSUE TITLE
Specify utf8 encoding in *one* place

### ISSUE THREAD

**Issue by uliska** [uliska/offlineimap#3]
It is not acceptable to have to add *two* configurations per account. This is tedious and error-prone.

I think there should be three places where this should be possible to define:

* In the account settings
* In the "general" section
* As a command line option

**Comment by nicolas33** [comment]
The expected level is the repository.  We have fallback mechanims to the upper levels when getting a user-defined configuration option.

**Comment by uliska** [comment]
Ah, OK? This implies that the user always has to add two or zero config options, otherwise it will probably fail.

**Comment by nicolas33** [comment]
Actually, the best grain level would be the folder. I guess this won't be possible at all.
Now, I realize that having this option at the repository level doesn't make much sense. You're right the account level is fine. OTOH, the offlineimap codebase does not always make it easy to use the correct level. This depends where you use the value.

**Comment by uliska** [comment]
Implemented

**Comment by nicolas33** [comment]
Does the current patch still allow the legacy nametrans?

**Comment by uliska** [comment]
Yes, they are totally independent.
The only thing that should probably be documented is the order of operations:

* Conversion *from* IMAP will first decode to utf-8 and later pass the result to a given nametrans function
* Conversion *to* IMAP will forst call nametrnas and will encode the result to IMAP_utf-7.

But as this option is new anyway this doesn't interfere with existing set-ups.

**Comment by nicolas33** [comment]
I was not clear enough, sorry. I'm thinking about the users currently running offlineimap.

1. Will users moving from decodefoldernames have to update their nametrans rules?
2. Will users have to update their nametrans if they enable/disable the utf8foldernames?

Honestly, I didn't check if decodefoldernames-enabled nametrans relies on utf-7 or utf-8 names. The current behaviour is not documented (which is bad, BTW).

There is a new note to add to the doc: how to use utf-8. Does the nametrans have to be decoded strings (u" "
 formatted)?

**Comment by uliska** [comment]
I must admit I am not totally clear in what order the current stable version oberates here. Probably users will have to *check* their `nametrans` function because - in IMAP=>Maildir direction - I think until now the `decode_mailbox_name` function is called *after* `nametrans` while in my code `nametrans` would (I'd say: correctly) be applied to the utf-8 encoded folder name. SO: if `nametrans` meddles with the characters that are affected by the re-encoding the order of operations may change the outcome, but if it only does things like stripping .INBOX parts or similar it should be equivalent.

The other direction is irrelevant as it doesn't exist until now.

**Comment by nicolas33** [comment]
> SO: if nametrans meddles with the characters that are affected by the re-encoding the order of operations may change the outcome, but if it only does things like stripping .INBOX parts or similar it should be equivalent.

Sure, the ASCII names won't be affected in nametrans.

So, it appears that updating the current `decodefoldenames` will have side effects and break setups. The best is to avoid touching it.

> The other direction is irrelevant as it doesn't exist until now.

Yes. This feature would be very nice to introduce while this could be done later in another step. ,-)
