### ISSUE TITLE
is the utf-7 file required?

### ISSUE THREAD

**Issue by nicolas33** [uliska/offlineimap#4]
We already have utf7 abilities in offlineimap. Why not improve the current code?

> This integration is far from ideal for several reasons:
> - the two procedures should never be used independently
  so it doesn't make sense to have two individual options

Sure.

> - they interfere (overwrite) any configuration for nametrans

Yes.

> - they interfere (partial redundancy) with decodefoldernames,
  which should (IMO) be removed

Either removed or superseded. I don't think introducing a new configuration option worth.

**Comment by uliska** [comment]
> We already have utf7 abilities in offlineimap. 

Do you mean `decode_mailbox_name()` in `imaputil.py`

> Why not improve the current code?

Actually (if the above assumption is correct) it was an attempt to keep the "experimental" code more separate, in its own file that is only imported when the user asks for the functionality.

>> they interfere (overwrite) any configuration for nametrans

>Yes.

Probably it should be integrated as suggested in #1 

>> they interfere (partial redundancy) with decodefoldernames, which should (IMO) be removed

> Either removed or superseded. I don't think introducing a new configuration option worth.

OK. I can imagine having `decodefoldernames` in the repository configuration sections. However, then the configuration parser would have to figure out if it is in a remote or local section, and I don't see yet how to accomplish that.

**Comment by uliska** [comment]
Stupid question (this is the first time I am confronted with this): Is this problem present with both IMAP<=>Maildir and Gmail<=>GmailMaildir or only with IMAP?

**Comment by nicolas33** [comment]
> Do you mean decode_mailbox_name() in imaputil.py

Yes.


> Actually (if the above assumption is correct) it was an attempt to keep the "experimental" code more separate, in its own file that is only imported when the user asks for the functionality.

The current 'decodefoldernames' is experimental. So, it's fine to play with.


> OK. I can imagine having decodefoldernames in the repository configuration sections.

I'm sorry I was not clear at all. I think the decodefoldernames option is in this section because of the code. I was expecting you to face the same issues regarding the code. If not, it's perfectly right to use the account section.

That's what I remember but I might be wrong, though.

> However, then the configuration parser would have to figure out if it is in a remote or local section, and I don't see yet how to accomplish that.

I'd suggest to do what you want. We'll discuss the code later.
Feel free to ping me but please be specific. Talking about code is usually much more efficient as long as producing the code does not consume too much time. ,-)

**Comment by nicolas33** [comment]
> Stupid question (this is the first time I am confronted with this): Is this problem present with both IMAP<=>Maildir and Gmail<=>GmailMaildir or only with IMAP?

AFAIR, all the reports we've had are about Maildir. I don't think IMAP/IMAP would be problematic.

**Comment by uliska** [comment]
https://github.com/uliska/offlineimap/commit/642071c64f993b930da49839215b26bbc049c480 makes the existing `decodefoldernames` option use the new code infrastructure and consequently removes the `decode_folder_names` function. Now there are three (four) ways to deal with the issue, and I don't need to decide on the issue:

* Have utf-7 support as a separate file (as per the current state of the branch) and either
    * import it only on request (as per current state of the branch) or  
      **pro:** only imported when necessary  
      **con:** `Import` check is performed for each folder in the function
    * import it at the top of the files  
      (pro/con inverse to the above)
* Move the utf-7 code to `imaputil`, effectively replacing the previous implementation  
  **pro:** one file/entity less to maintain, the functionality "natively" belongs to imap utilities  
  **con:** code is parsed even when not requested by config

My suggestion would be to go for the last option. What do you think @nicolas33 ?

**Comment by nicolas33** [comment]
The last option is the correct one. We don't care how it's used. Decoding UTF-7 to UTF-8 is only one feature so there must be only one API.

**Comment by uliska** [comment]
OK, I'll do so once the current code has become stable again (I had started poking around with understanding what happens when in which order ;-)
